# Default values for Quote of the Day system.

qotdbackend:
  image: "quay.io/rhdevelopers/qotd:db"
  dbpassword: "reallylongpassword99!"
  dbstorage: "8Gi"
  dbhost: "postgres"
  dbuser: "qotd"
  dbname: "quotesdb"
     
qotdwebsite:
  image: "quay.io/rhdevelopers/qotd-website-nodejs:latest"

frontend:
  replicas: 1

backend:
  replicas: 1

route:
  enabled: true

service:
  port: 8080
