apiVersion: v1
kind: Secret
metadata:
  name: postgresql-secret
  labels:
    {{- include "qotdsystem.labels" . | nindent 4 }}
stringData:
  SERVICE_NAME: postgresql
  POSTGRES_DB: quotesdb
  POSTGRES_USER: qotd
  POSTGRES_PASSWORD: {{ .Values.qotdbackend.dbpassword | quote }}
