apiVersion: v1
kind: Service
metadata:
  name: qotd-website
  labels:
    {{- include "qotdsystem.labels" . | nindent 4 }}
    app: qotd-website
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: qotd-website
  type: ClusterIP
